version: '3'
services:
  app:
    image: rachsharp/feedbin
    ports:
      - 9292:9292
  postgres:
    image: postgres
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    expose:
      - 6379
    volumes:
      - redis_data:/data
  memcached:
    image: memcached
    expose:
      - 11211
  elasticsearch:
    image: elasticsearch:2.4.6
    expose:
      - 9200
  refresher:
    image: rachsharp/feedbin-refresher
  camo:
    image: inventid/camo
    expose:
      - 8081
volumes:
  redis_data:
  postgres_data:
